import './global.css';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { Container } from '@/components';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

import { CssBaseline, ThemeProvider } from '@mui/material';
import { theme } from '@/theme';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontSans.className}>
        <AppRouterCacheProvider options={{ key: 'css' }}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <Container>{children}</Container>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
